name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 551561343088.dkr.ecr.ap-south-1.amazonaws.com

      - name: Pull image from ECR
        run: docker pull 551561343088.dkr.ecr.ap-south-1.amazonaws.com/serverless-repo:latest

      - name: Deploy to AWS App Runner
        run: |
          aws apprunner start-deployment \
            --service-arn arn:aws:apprunner:ap-south-1:551561343088:service/app-runner-service
          
